### ISSUE TITLE
BLAYSYS Installation PreReq Challenges.  Docker image available?

### ISSUE THREAD

**Issue by techmonte** [scale-lab/BLASYS#5]
@Ace-Ma @sheriefreda, I tried following the installation instructions for setting up BLASYS and am running into problems with building abc (NOTE: The instructions for compiling abc is error-prone and a number of issues have been logged in that GitHub repo) as part of the BLASYS prerequisites.

Would the scale-lab team happen to have a Docker image with everything properly installed that they'd be willing to share?

**Comment by jingxiao-ma** [comment]
@techmonte I am sorry that we do not have a Docker image right now. I am currently working on it and will post the Docker file as soon as possible. Meanwhile, do you have a build of Yosys? If so, there is an executable named `yosys-abc` inside the top folder, which can exactly be used for our purpose. 
Sorry for the inconvenience.

**Comment by techmonte** [comment]
@Ace-Ma , thanks for the reply.  Don’t have a build of Yosys, but will take a look.  Thanks for your response! 🙂
