### ISSUE TITLE
lsoracle reports an error when running blasys.py

### ISSUE THREAD

**Issue by 01xz** [scale-lab/BLASYS#6]
hi, i tried to run the test samples but the lsoracle end up with an error "[e] unknown command: get_all_partitions"

i noticed that the master branch of lsoracle does not provide the command "get_all_partitions"
see line90 in [lsoracle.cpp](https://github.com/lnis-uofu/LSOracle/blob/master/core/lsoracle.cpp)

would you tell me which branch to use if i want to run these test samples?

**Comment by KushagraGupta02** [comment]
Hi @01xz , could you share the LSOracle binary built on Linux (Ubuntu 20.04) or please let me know the fix to this issue if you were able to resolve it?- it would be a really great help, thank you!
