### ISSUE TITLE
partition command error 

### ISSUE THREAD

**Issue by macaron009** [scale-lab/BLASYS#7]
In the latest LSOracle, the following commands have been removed. 
- partitioning
- get_all_partitions

Which version of LSOracle did you use to build your environment?

**Comment by KushagraGupta02** [comment]
Hi @macaron009, could you share the LSOracle binary built on Linux (Ubuntu 20.04) or please let me know the fix to this issue if you were able to resolve it?- it would be a really great help, thank you!
